version: "3.8"

services:
    frontend:
        build: .
        ports:
            - "8081:80" # Expose frontend on port 8081
        environment:
            - VITE_PIPED_API=https://api.vidioo.ir
            - VITE_PIPED_PROXY=https://pipedproxy.kavin.rocks
            - VITE_SITE_NAME=vidioo
            - VITE_DEFAULT_LANGUAGE=fa
            - VITE_CALENDAR_TYPE=jalali
            - VITE_DISABLE_COMMENTS=true
            - VITE_DISABLE_LIKES_DISLIKES=true
            - VITE_DISABLE_LIVESTREAMS=true
            - VITE_DISABLE_DOWNLOAD_THUMBNAIL=true
            - VITE_DISABLE_THEME_SELECTOR=true
            - VITE_DISABLE_WATCH_ON_YOUTUBE=false
            - VITE_DISABLE_WATCH_HISTORY_STORAGE=false
            - VITE_DISABLE_SEARCH_HISTORY_STORAGE=true
            - VITE_DISABLE_SEARCH_SUGGESTIONS=true
            - VITE_DISABLE_LBRY_INTEGRATION=true
            - VITE_DISABLE_LBRY_PROXY=true
            - VITE_DISABLE_PREFETCH_LIMIT=true
            - VITE_DISABLE_DEARROW_INTEGRATION=true
            - VITE_DISABLE_RSS_FEED=true
            - VITE_DISABLE_IMPORT_EXPORT=true
            - VITE_DISABLE_ADD_TO_GROUP=true
            - VITE_DISABLE_RECOMMENDATIONS_TOGGLE=true
            
            - VITE_DISABLE_CHAPTERS=true
            - VITE_DISABLE_VIDEO_ITEM_ICONS=true
            - VITE_DISABLE_LICENSE_INFO=true
            - VITE_COUNTRY_REGION=US
            - VITE_BUFFERING_GOAL=30
            - VITE_CDN_THUMBNAIL_BASE_URL=https://thumbs.media.edgekey.ir/vi/
            - VITE_ENABLE_CDN=false
            - VITE_CDN_URL=https://media.vidioo.ir
        restart: unless-stopped

volumes: {}
